name: 'AWS EC2 Start and Stop'
description: 'Start and Stop an AWS EC2 Instance with the AWS CLI'
branding:
  icon: 'play'  
  color: 'orange'
inputs:
  instance-id:  
    description: 'Instance ID'
    required: true
  wait-instance-running:
    description: 'Wait until the instance is running'  
    default: true
  stop-instance:
    description: 'Stop the instance during post job cleanup'  
    default: true    
outputs:
  current-state: 
    description: 'The current state of the instance'
  previous-state: 
    description: 'The previous state of the instance'    
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'